global:
  # NT-Domain-Name or Workgroup-Name
  workgroup: "MyGroup"
  #server string is the equivalent of the NT Description field
  server: "Samba Server"

  # Apple extensions ("AAPL") run under SMB2/3 protocol, make that the minimum (probably shouldn't be running
  # SMB1 anyway...) - defaults to SMB2_2 in Samba 4.11+:
  minProtocol: "SMB2"
  #Apple extensions require support for extended attributes(xattr) - defaults to yes in Samba 4.9+:
  eaSupport: "yes"
  # Load in modules (order is critical!) and enable AAPL extensions:
  vfsObjects: "fruit streams_xattr"
  # https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html
  fruits:
    - fruit:aapl = yes
    - readdir_attr:aapl_rsize = yes
    - readdir_attr:aapl_finder_info = yes
    - readdir_attr:aapl_max_access = yes

    - fruit:metadata = stream
    - fruit:model = MacSamba
    - fruit:veto_appledouble = no
    - fruit:posix_rename = yes
    - fruit:zero_file_id = yes
    - fruit:wipe_intentionally_left_blank_rfork = yes
    - fruit:delete_empty_adfiles = yes
  # any further global options you want to put into the script
  extra: []

shares:
  - name: "home"
    browseable: "no"
    writeable: "yes"
    path: "/home/user/"
    guestAllowed: "no"
    comment: "Home dir"
    writeList: "@staff"
    validUsers:
      - "foouser"
      - "fred"
    createMask: "0765"
    extra:
      - "foo = bar"

users:
  - name: "foouser"
    password: "qwerty"
    id: 500



